name: Client Test Site
favicon: null
layout_spectrum: 0.5262820236384869
typography_spectrum: 0.708223850466311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f95634'
    - '#ccc547'
    - '#3d0353'
    - '#c1006b'
    - '#ffffff'
  brandStrength: 0.4770218494813889
  lightness: 0.7887449520640075
  saturation: 0.8167693689465523
  rhythmicContrast: 0.8242771888617426
purpose: []
